### ISSUE TITLE
Lego hangs after "server validated our request" sometimes

### ISSUE THREAD

**Issue by mholt** [go-acme/lego#1075]
We now have several similar reported instances of the lego logs printing:

```
...
2020/03/05 05:44:14 [INFO] [...] acme: use http-01 solver
2020/03/05 05:44:14 [INFO] [...] acme: Trying to solve HTTP-01
2020/03/05 05:44:20 [INFO] [...] The server validated our request
```

and then hanging.

Reports are here:

- https://caddy.community/t/https-certificate-hang/7157?u=matt
- https://caddy.community/t/v2-why-wasnt-cert-available-after-reload-restart-only-after-reboot/7020?u=matt
- https://caddy.community/t/v2-why-wasnt-cert-available-after-reload-restart-only-after-reboot/7020/7?u=matt

These reports appear to have identical behavior. The final log line is supposedly printed from this code: https://sourcegraph.com/github.com/go-acme/lego@b5d99c7b1405d23d71cca8bd4d865379e704474a/-/blob/challenge/resolver/solver_manager.go#L128

The next log line that usually immediately follows is _not_ printed:  https://sourcegraph.com/github.com/go-acme/lego@v3.4.0/-/blob/certificate/certificates.go#L121

So that leads me to think that the backoff/retry function never returns: https://sourcegraph.com/github.com/go-acme/lego@v3.4.0/-/blob/challenge/resolver/solver_manager.go#L135

But I do not know why. Have you encountered this problem before?

**Comment by ldez** [comment]
What version of lego are you using?

**Comment by mholt** [comment]
Versions 3.2, 3.3, and 3.4 all seem to be affected, as far as I can tell.

**Comment by mholt** [comment]
Additional experience report: I am also seeing this behavior myself a lot today, setting up a new (unimportant) production site.

**Comment by mholt** [comment]
Still happening with lego 3.5.

**Comment by ldez** [comment]
As I'm not able to reproduce, this issue is still open and no changes have been made to correct this issue, so yes the v3.5 don't fix this problem.

There are two ways to get this message:
- a `valid` authorization status
- a `valid` challenge status

If there is an issue with lego, I don't think that is related to backoff.

I don't know the code of cert-magic and caddy, so I don't know how the certificates are stored or get.

I cannot do more from my side without a reproduction.

**Comment by mholt** [comment]
Okay, I'll see if we can reproduce it reliably in the future.
