### ISSUE TITLE
Add "directadmin" as DNS option

### ISSUE THREAD

**Issue by smtalk** [go-acme/lego#1101]
It'd be great if DirectAdmin could be added as a DNS option for DNS cert issuance. It'd simply add the record to local DNS zone (bind) or sync it to a remote DNS server.

Add record (replace ${single_domain} with any domain name, www.domain.com, domain.com etc.):
```
echo "action=dns&do=add&domain=${single_domain}&type=TXT&name=_acme-challenge-test&value=\"pre-check\"&ttl=5&named_reload=yes" >> /usr/local/directadmin/data/task.queue.cb
/usr/local/directadmin/dataskq --custombuild
```

Remove it:
```
echo "action=dns&do=delete&domain=${single_domain}&type=TXT&name=_acme-challenge" >> /usr/local/directadmin/data/task.queue.cb
/usr/local/directadmin/dataskq --custombuild
```

Thank you!

**Comment by ldez** [comment]
Hello,

I don't know how this tool works exactly, but I understand that it can be controlled by a CLI.

So in this case you can use the [exec](https://go-acme.github.io/lego/dns/exec/) to executed the commands to Injects and clean the response payloads.

You can share your scripts (run by the [exec provider](https://go-acme.github.io/lego/dns/exec/)) in this issue to help the others DirectAdmin users.

We will not create a dedicated implementation that use the CLI because we only create a dedicated implementation for HTTP API.

I found only few information about the HTTP API, the only page thet I found is really light.

https://www.directadmin.com/features.php?id=504

If someone want to create an implementation, base on the HTTP API, feel free to open a PR.

**Comment by jwklijnsma** [comment]
@ldez will make the code next optie next weeks when i have free time

**Comment by FirefoxNL** [comment]
@jwklijnsma Any chance you've had the time to look into this? :)

For reference, Certbot already has a DirectAdmin plugin. [Available here](https://github.com/cybercinch/certbot-dns-directadmin/blob/master/certbot_dns_directadmin/directadmin.py).
Although it is in Python, it might help with implementing it here.

**Comment by jwklijnsma** [comment]
@FirefoxNL i have working version local will make pr this weekend

**Comment by jwklijnsma** [comment]
@ldez Will create pr the correct one this weekend need fix unit test for it
