### ISSUE TITLE
renew command should give a non-zero exit code if the passed domains do not match an existing certificate

### ISSUE THREAD

**Issue by ryantm** [go-acme/lego#1156]
Hi.

Following up on #1155, as @ldez said there, it doesn't make sense to renew a certificate that has an additional alternative name added and this should be a new certificate, so if the list of domains passed to the renew command doesn't match the domains of a certificate that is already issued, it should return a non-zero exit code, so that renewal failure can be detected and the caller may try the `run` command.

Ryan

**Comment by ldez** [comment]
Hello,

It's a bit more ambiguous: because if you define the right number of days, you can revew and add a new certificate.

Some lego's users, use that behavior, if we change this behavior to throw an error it will be a breaking change.

As I referenced in #1155, this is something we will change when we create a unified order to execute / renew. (related to #693, #290, #216, #221)
