### ISSUE TITLE
Support azure cli authentication

### ISSUE THREAD

**Issue by elliots** [go-acme/lego#1205]
Hi, I'd like to authenticate using the az cli and avoid any env vars. 
Terraform uses https://github.com/hashicorp/go-azure-helpers/tree/master/authentication to support it.

Is this something anyone has looked at?

I'm happy to put together a PR, would calling out to the library just for cli be ok?

**Comment by ahmad-hamade** [comment]
@ldez May you please advise on this issue?

@elliots/myself can work on a PR to use hashicorp/go-azure-helpers for Azure authentication instead of the current implementation.

**Comment by ldez** [comment]
I don't want to create something specifically for one DNS provider, the current behavior is to use env vars.
You have to keep in mind that lego is a CLI but mainly a lib.

But currently, I don't know what `hashicorp/go-azure-helpers` adds exactly and how this can be integrated without too much impact on the main behavior.
Then you can try to create a PR like that I will be able to show the impact, but I don't promise that I will merge the PR.

**Comment by ahmad-hamade** [comment]
Thank you @ldez for sharing your feedback and you are right at the point where lego is also used as a library (sorry, I just missed that)

Do you suggest any alternative approach for implementing the other supported azure authentications?

I'm looking at this list:
https://github.com/hashicorp/go-azure-helpers/tree/master/authentication

I will be happy to put a PR for this change.

**Comment by hargut** [comment]
Hi @ldez,

I think this issue is not directly related to terraform or a DNS provider for terraform and could as well very useful within the library.
Likely the requests for the support of OIDC federated credential flow from Azure is more often requested from terraform users as their providers typically have full support for that flow.

The OIDC flow federated credentials allows to trust another OIDC provider for accessing a service principal without static secrets:
https://learn.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0

From a technical perspective this can be done through REST requests on OIDC token endpoints. The flows are well integrated with Github Actions and for this use case the requests look like:

Get the Id Token from the trusted OIDC provider (in this case Github):
```node
const audience = core.getInput('audience', {required: false}) || "api://AzureADTokenExchange"

let id_token_url = process.env['ACTIONS_ID_TOKEN_REQUEST_URL']
if (audience) {
    const encodedAudience = encodeURIComponent(audience);
    id_token_url = `${id_token_url}&audience=${encodedAudience}`;
}
const res = httpclient.getJson(id_token_url)
let githubIdToken = res.result;
```
Use e.g. the client_credentials flow to obtain a service principal bearer token
```node
async function getAzureIdToken(azureTenantId, azureClientId, azureTokenScope, githubIdToken) {
    if (!azureTokenScope) {
        azureTokenScope = "https://graph.microsoft.com/.default"
    }

    let bearer = {
        url: `https://login.microsoftonline.com/${azureTenantId}/oauth2/v2.0/token`,
        method: 'POST',
        headers: {'content-type': 'application/x-www-form-urlencoded'},
        data: {
            grant_type: "client_credentials",
            client_assertion_type: 'urn:ietf:params:oauth:client-assertion-type:jwt-bearer',
            client_id: azureClientId,
            client_assertion: githubIdToken,
            scope: azureTokenScope
        }
    }
    return await axios.request(bearer)
        .then(function (response) {
            return response.data.access_token
        })
}
```

Best regards,
Harald
