### ISSUE TITLE
Please add Nextdns to supported DNS providers

### ISSUE THREAD

**Issue by sjdmd** [go-acme/lego#1249]
Please add nextdns (https://nextdns.io) to the list of supported DNS providers if at all possible. Thank you. /Steve

**Comment by ldez** [comment]
Hello,

We (the lego maintainers) don't have or manage an account in all DNS providers in the world.

In order to help someone who would like to create a PR on the subject, a link to the API documentation is needed.

It is only possible to automate DNS providers that have an API for manipulating TXT records.

By default, we do not add a DNS provider that we are not able to handle.
It is therefore necessary that a contributor having an account for the DNS provider:
- either creates a PR and be able to maintain the implementation for the DNS provider
- or a contributor ables to test an implementation.

**Comment by ldez** [comment]
nextdns seems to not be a DNS provider, but just a DNS relay for a device.

**Comment by sjdmd** [comment]
I'm in no position to argue with you. They do offer relaying so that all devices on a network are forced into using them as the DNS provider. They do this by capturing all Port 53 traffic. See https://github.com/nextdns/nextdns/wiki. 

I am a netdns user and I can and would test an implementation done by others through the use of https://github.com/kchristensen/udm-le

Thank you./Steve

**Comment by ldez** [comment]
I think you are mixing DNS API and DNS.

In lego, what we call a DNS provider is related to an API to add and remove records for a domain.

NextDNS is just a recursive DNS server.
