### ISSUE TITLE
Cloudflare can't find zone for sub-domain

### ISSUE THREAD

**Issue by lexfrei** [go-acme/lego#1303]
I'm trying to issue a certificate for my internal service `longhorn.k8s.home.lex.la` with traefik and facing the error:

```
time="2020-11-23T21:05:13Z" level=error msg="Unable to obtain ACME certificate for domains \"longhorn.k8s.home.lex.la\": unable to generate a certificate for the domains [longhorn.k8s.home.lex.la]: error: one or more domains had a problem:\n[longhorn.k8s.home.lex.la] [longhorn.k8s.home.lex.la] acme: error presenting token: cloudflare: failed to find zone k8s.home.lex.la.: Zone could not be found\n" providerName=stagessl.acme routerName=longhorn-ingress-longhorn-system-longhorn-k8s-home-lex-la@kubernetes rule="Host(`longhorn.k8s.home.lex.la`)"
```

The token rights looks fine:
![image](https://user-images.githubusercontent.com/1366514/100017889-a04f1080-2dec-11eb-9eda-450e87f14f5c.png)

Looks similar too:
https://github.com/go-acme/lego/issues/1021

Is it my failure or something went wrong on CF's side?

**Comment by ldez** [comment]
Hello,

the error `Zone could not be found` comes from Cloudflare, the potential causes are:
- there is no zone for the given zone name
- the zone is not attached to the right AccountID

It doesn't seem related to lego.

https://go-acme.github.io/lego/dns/cloudflare/#api-tokens

**Comment by lexfrei** [comment]
@ldez, I can issue a certificate for `longhorn.lex.la`, but can't for `longhorn.k8s.home.lex.la` with same config. Isn't it proof of a valid token?
I'm trying to find any additional settings/info in CF about this, but I'm a newbie about CF.

**Comment by waynema02** [comment]
I have a very similar issue, and this only popped up in the last couple of days. 

```
time="2020-11-28T12:21:04-08:00" level=debug msg="legolog: [INFO] [xxx.xxxx.net] acme: Could not find solver for: tls-alpn-01"
time="2020-11-28T12:21:04-08:00" level=debug msg="legolog: [INFO] [xxx.xxxx.net] acme: Could not find solver for: http-01"
time="2020-11-28T12:21:04-08:00" level=debug msg="legolog: [INFO] [xxx.xxxx.net] acme: use dns-01 solver"
time="2020-11-28T12:21:04-08:00" level=debug msg="legolog: [INFO] [xxx.xxxx.net] acme: Preparing to solve DNS-01"
time="2020-11-28T12:21:08-08:00" level=debug msg="legolog: [INFO] [xxx.xxxx.net] acme: Cleaning DNS-01 challenge"
time="2020-11-28T12:21:12-08:00" level=debug msg="legolog: [WARN] [xxx.xxxx.net] acme: cleaning up failed: cloudflare: failed to find zone net.: Zone could not be found "
```

I'm using traefik as reverse proxy, and all the cert are generated correctly until the last week.

To further narrow down the problem, using the same cloudflare API configuration, I tried both traefik, caddy, and certbot. Neither traefik nor caddy can get a new certificate using dns challenge. However, with the same cloudflare API configuration, certbot actually can get a new certificate.  

Thanks

**Comment by ldez** [comment]
> cloudflare: failed to find zone net.: Zone could not be found 

@waynema02 it's not the same error. You have an error during the cleaning but it's just a warning.

But from your error message, which not the same as for the issue reporter, I can say that you have an issue with the DNS resolvers.

So you have to override your local resolvers:
- with lego [`--dns.resolvers`](https://go-acme.github.io/lego/usage/cli/#usage)
- with Traefik [`acme.dnsChallenge.resolvers`](https://doc.traefik.io/traefik/v2.3/https/acme/#resolvers)

**Comment by waynema02** [comment]
@ldez really appreciate the prompt response!

I'll try the check the correct resolvers option, and report back

**Comment by waynema02** [comment]
@ldez [Your suggestion](https://github.com/go-acme/lego/issues/1303#issuecomment-735289513) works perfectly! 

I just add the `resolvers` option to my `traefik.yaml`: 

```
certificatesResolvers:
  myresolver:
    acme:
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 8.8.8.8:53
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      storage: "/letsencrypt/acme.json"
```

And the cert is correctly requested:

```
time="2020-11-28T13:25:28-08:00" level=debug msg="legolog: [INFO] [xxxx.xxxx.net] acme: Obtaining bundled SAN certificate"
time="2020-11-28T13:25:28-08:00" level=debug msg="legolog: [INFO] [xxxx.xxxx.net] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/163860402"
time="2020-11-28T13:25:28-08:00" level=debug msg="legolog: [INFO] [xxxx.xxxx.net] acme: Could not find solver for: tls-alpn-01"
time="2020-11-28T13:25:28-08:00" level=debug msg="legolog: [INFO] [xxxx.xxxx.net] acme: Could not find solver for: http-01"
time="2020-11-28T13:25:28-08:00" level=debug msg="legolog: [INFO] [xxxx.xxxx.net] acme: use dns-01 solver"
time="2020-11-28T13:25:28-08:00" level=debug msg="legolog: [INFO] [xxxx.xxxx.net] acme: Preparing to solve DNS-01"
time="2020-11-28T13:25:32-08:00" level=debug msg="legolog: [INFO] cloudflare: new record for xxxx.xxxx.net, ID xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
time="2020-11-28T13:25:32-08:00" level=debug msg="legolog: [INFO] [xxxx.xxxx.net] acme: Trying to solve DNS-01"
time="2020-11-28T13:25:32-08:00" level=debug msg="legolog: [INFO] [xxxx.xxxx.net] acme: Checking DNS record propagation using [1.1.1.1:53 8.8.8.8:53]"
time="2020-11-28T13:25:34-08:00" level=debug msg="legolog: [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]"
time="2020-11-28T13:25:46-08:00" level=debug msg="legolog: [INFO] [xxxx.xxxx.net] The server validated our request"
time="2020-11-28T13:25:46-08:00" level=debug msg="legolog: [INFO] [xxxx.xxxx.net] acme: Cleaning DNS-01 challenge"
time="2020-11-28T13:25:46-08:00" level=debug msg="legolog: [INFO] [xxxx.xxxx.net] acme: Validations succeeded; requesting certificates"
time="2020-11-28T13:25:49-08:00" level=debug msg="legolog: [INFO] [xxxx.xxxx.net] Server responded with a certificate."
```

In retrospect, I did setup a `pihole` a few days ago, and pointed all my servers to it. Probably since then I cannot get any new certificate. Maybe somehow the `pihole` interfered with the FQDN resolve? That's a bit weird.. Anyway, getting all the DNS pieces right is always a struggle for me :(

My issue is fully resolved. Thanks!

**Comment by lexfrei** [comment]
@ldez look at this:
([gist](https://gist.github.com/lexfrei/4b5b16290927d746bb8d212f0ce06c6d))
```shell
$ go run . <TOKEN>
2020/11/29 02:07:43 trying to login...
2020/11/29 02:07:43 logged in!

2020/11/29 02:07:43 trying to get zone ID like lego tries to do so...
2020/11/29 02:07:43 k8s.home.lex.la is in use
2020/11/29 02:07:46 Ofc, it's not working: Zone could not be found

2020/11/29 02:07:46 trying to get zone ID by short domain...
2020/11/29 02:07:47 lex.la is in use
2020/11/29 02:07:47 zone id is: 8e3fd4280829357a4081156b0028442f

2020/11/29 02:07:47 trying to create TXT in this zone...
2020/11/29 02:07:48 done!

2020/11/29 02:07:48 trying retrieve TXT by ID...
2020/11/29 02:07:50 longhorn.k8s.home.lex.la    TXT     hi, lego!
:)
```

Feel free to test it with `dig -t txt longhorn.k8s.home.lex.la`

Looks like lego should use just a second-level domain to retrieve zone id and trim the domain, not like [this](https://github.com/go-acme/lego/blob/136f159d53aed184119ccc603c5f84977adbe1f0/providers/dns/cloudflare/client.go#L82)

I'm not familiar with CF's API so, I can't create a PR with fix by myself, sorry.

**Comment by ldez** [comment]
I think there is no problem with lego.

Have you tried the solution I suggested to waynema02? I think you're dealing with a DNS cache problem.

https://github.com/go-acme/lego/issues/1303#issuecomment-735289513

**Comment by lexfrei** [comment]
@ldez oh. My bad. Just tried the lego itself and it works!
But, there is a way how I can reproduce the traefik's `Zone could not be found` error for domains with more than 3 levels.
Let me investigate it a little more and I'll close this issue.
Sorry for blaming the lego.

**Comment by rptaylor** [comment]
Sorry to comment on an old issue, but this doesn't really indicate what the problem is with the DNS server, or how to fix it.
Using a different DNS resolver sidesteps the issue. 
If you get the "could not find zone for domain " error, what is the issue that needs to be fixed with the DNS server?

**Comment by ldez** [comment]
@rptaylor can you open a dedicated issue? thank you

**Comment by Redsandro** [comment]
I just want to SEO this because I have spent **hours** on this, with both ChatGPT and duckduckgo giving me the runaround. The [solution](https://github.com/go-acme/lego/issues/1303#issuecomment-735294970) by @waynema02 / @ldez resolved my issue:

> I just add the `resolvers` option to my `traefik.yaml`:
> 
> ```
> certificatesResolvers:
>   myresolver:
>     acme:
>       dnsChallenge:
>         provider: cloudflare
>         resolvers:
>           - 1.1.1.1:53
>           - 8.8.8.8:53
> ```
> 
> And the cert is correctly requested:

I can't understand what causes this problem because I've migrated the exact same configuration of Traefik on a Debian 12 LXC in Proxmox - which was running fine for half a year - to an Alpine LXC (in order to save resources). On the same local network. Yes, I also have pi-hole as a DNS configured in my router. But no, that was not a problem for my original Traefik on Debian.

The pi-hole is running in traefik as well, it was not my first vm in Proxmox. That means that the first domain in Traefik was requested before pi-hole DNS was set up, and domains I added later were post pi-hole.

This leads me to believe that the above configuration is only required for the first cert request run on a new Traefik. Once it has been successful, it is not necessary anymore when adding new routes with new domains. But I am not sure.

I'm happy it finally works and so out of time allotted for this project that I don't dare to try and remove the resolvers from the configuration to see if new and updated certificates will still successfully be requested.

**Comment by rptaylor** [comment]
For anyone googling this, I think this indicates an underlying issue in the system DNS resolvers used by your pods / nodes, at least in our case, it was that SOA lookups using DNSSEC (which may require using TCP instead of UDP) were failing:

```
dig <domain> SOA +dnssec

dig +tcp <domain> SOA +dnssec
```
where `<domain>` is  e.g. _acme-challenge.foo.example.org, foo.example.org, or example.org.

By specifying 1.1.1.1 or 8.8.8.8 you can work around it, but it's better to fix the underlying issue in your DNS.

**Comment by chunjiw** [comment]
I ran into the same issue on NixOS. My setup had been working fine for 3+ years before it suddenly broke last month. Adding explicit `resolvers` to the `dnsChallenge` config in Traefik fixed it. Both `dig` tests on my local DNS passed fine, so the issue seems to be with how lego resolves DNS internally rather than the local DNS setup itself.

**Comment by ldez** [comment]
> My setup had been working fine for 3+ years before it suddenly broke last month.
> ...
> so the issue seems to be with how lego resolves DNS internally rather than the local DNS setup itself.

No the problem is related to your network.

lego is only doing DNS calls, nothing special.
It relies on your local network.
