### ISSUE TITLE
Support for DNS Api from hoster all-inkl.com (kasserver)

### ISSUE THREAD

**Issue by gerribaldi** [go-acme/lego#1328]
Hi all,

is there a way to add the german provider all-inkl.com to the dnsChallenge? I found on github a repro with some [code ](https://github.com/fetzerch/kasserver) and also a link to the [api ](https://kasapi.kasserver.com/) from all-inkl.com. I guess that this will help to get it into lego.

Would be nice to this in one of the next releases. Thanks a lot 

regards
gerribaldi

**Comment by 42Technology** [comment]
i would second an inclusion in the providers

**Comment by ldez** [comment]
Hello @42Technology,

I can work on it, the problem is the old SOAP API...
If you can provide me an account with a domain it will really useful.

PS: I'm the main maintainer of lego https://github.com/go-acme/lego/graphs/contributors

**Comment by 42Technology** [comment]
Hello @ldez ,

no problem with the account is there a private way to give it to you ?

best regards
Alex

**Comment by ldez** [comment]
you can contact me on the Gopher's slack https://gophers.slack.com

**Comment by ldez** [comment]
Thank you @42Technology :+1: 

I created and tested the implementation with your account everything works :tada:

**Comment by 42Technology** [comment]
great to hear it, and glad i could help with an account

**Comment by ldez** [comment]
It was a bit difficult because the documentation is more PHP client doc than API documentation, it's a SOAP service with PHP's style structuration (the famous PHP "array" type), and dynamic types with a typed language is always something complex.
I did a lot of transformation to get something that I can use.

Not an easy job to play with this API, but I think my implementation is clean.
