### ISSUE TITLE
Porkbun returning Error 400: Invalid Domain

### ISSUE THREAD

**Issue by gbakeman** [go-acme/lego#1754]
It looks like an error was introduced between versions 4.8.0 and 4.9.0. I've been trying to troubleshoot this with Porkbun's support and they were stumped, because I was using Traefik at the time and didn't realize this happened as a result of an update with lego. As a side note, it would be nice to see the raw API payload for debugging purposes (maybe a command line argument?), at least as the support department would like to see it.

### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

A successful `run` operation to obtain a certificate for a requested domain from Porkbun's ACME Let's Encrypt service:

`docker run --env-file ./pkbun-secrets.txt  goacme/lego:v4.8.0 --email [my email] --dns porkbun --domains service.subdomain.domain.tld  --accept-tos run`

```
2022/11/05 21:01:55 No key found for account [my email]. Generating a P256 key.
2022/11/05 21:01:55 Saved key to /.lego/accounts/acme-v02.api.letsencrypt.org/[my email]/keys/[my email].key
2022/11/05 21:01:55 [INFO] acme: Registering account for [my email]
2022/11/05 21:01:55 [INFO] [service.subdomain.domain.tld] acme: Obtaining bundled SAN certificate
2022/11/05 21:01:55 [INFO] [service.subdomain.domain.tld] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/172802458067
2022/11/05 21:01:55 [INFO] [service.subdomain.domain.tld] acme: Could not find solver for: tls-alpn-01
2022/11/05 21:01:55 [INFO] [service.subdomain.domain.tld] acme: Could not find solver for: http-01
2022/11/05 21:01:55 [INFO] [service.subdomain.domain.tld] acme: use dns-01 solver
2022/11/05 21:01:55 [INFO] [service.subdomain.domain.tld] acme: Preparing to solve DNS-01
2022/11/05 21:01:56 [INFO] [service.subdomain.domain.tld] acme: Trying to solve DNS-01
2022/11/05 21:01:56 [INFO] [service.subdomain.domain.tld] acme: Checking DNS record propagation using [local dns]
2022/11/05 21:02:06 [INFO] Wait for propagation [timeout: 10m0s, interval: 10s]
2022/11/05 21:02:09 [INFO] [service.subdomain.domain.tld] The server validated our request
2022/11/05 21:02:09 [INFO] [service.subdomain.domain.tld] acme: Cleaning DNS-01 challenge
2022/11/05 21:02:10 [INFO] [service.subdomain.domain.tld] acme: Validations succeeded; requesting certificates
2022/11/05 21:02:10 [INFO] [service.subdomain.domain.tld] Server responded with a certificate.
```

### What did you see instead?

An error 400: Invalid Domain error message, and an unknown record ID from Porkbun (likely as a result.)

`docker run --env-file ./pkbun-secrets.txt  goacme/lego:v4.9.0 --email [my email] --dns porkbun --domains service.subdomain.domain.tld  --accept-tos run`

```
2022/11/05 20:43:54 No key found for account [my email]. Generating a P256 key.
2022/11/05 20:43:54 Saved key to /.lego/accounts/acme-v02.api.letsencrypt.org/[my email]/keys/[my email].key
2022/11/05 20:43:54 [INFO] acme: Registering account for [my email]
2022/11/05 20:43:54 [INFO] [service.subdomain.domain.tld] acme: Obtaining bundled SAN certificate
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2022/11/05 20:43:55 [INFO] [service.subdomain.domain.tld AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/172798047087
2022/11/05 20:43:55 [INFO] [service.subdomain.domain.tld acme: Could not find solver for: tls-alpn-01
2022/11/05 20:43:55 [INFO] [service.subdomain.domain.tld acme: Could not find solver for: http-01
2022/11/05 20:43:55 [INFO] [service.subdomain.domain.tld acme: use dns-01 solver
2022/11/05 20:43:55 [INFO] [service.subdomain.domain.tld acme: Preparing to solve DNS-01
2022/11/05 20:44:15 [INFO] [service.subdomain.domain.tld acme: Cleaning DNS-01 challenge
2022/11/05 20:44:25 [WARN] [service.subdomain.domain.tld acme: cleaning up failed: porkbun: unknown record ID for 'pixie.porkbun.com.' 'long string ID'
2022/11/05 20:44:25 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/172798047087
2022/11/05 20:44:25 Could not obtain certificates:
        error: one or more domains had a problem:
[service.subdomain.domain.tld [service.subdomain.domain.tld acme: error presenting token: porkbun: failed to create record: 400: {"status":"ERROR","message"
:"Invalid domain."}
```
### How do you use lego?

Docker image

### Version of lego

```console
4.8.0 (fine), 4.9.0 (bug)
```

</details>

**Comment by ldez** [comment]
Hello,

there is no change about the Porkbun in v4.9.0.

https://github.com/go-acme/lego/compare/v4.8.0...v4.9.0

**Comment by gbakeman** [comment]
I've just run both commands within the space of ~20 minutes of each other, so definitely something I can replicate on my end by changing versions. You don't by any chance have a porkbun account you can verify with? I'll pass this along to their support but I don't know if they're willing to take a deep dive for me.

**Comment by ldez** [comment]
The following error:
```
2022/11/05 20:44:25 Could not obtain certificates:
        error: one or more domains had a problem:
[service.subdomain.domain.tld [service.subdomain.domain.tld acme: error presenting token: porkbun: failed to create record: 400: {"status":"ERROR","message"
:"Invalid domain."}
```

lead me to think that you have a CNAME, check your DNS configuration.

Try to set the env var `LEGO_DISABLE_CNAME_SUPPORT` to `true`.

**Comment by ldez** [comment]
The information you added to your previous one confirms what I thought.

This wildcard CNAME is a problem:
> CNAME | *.domain.tld | pixie.porkbun.com

**Comment by gbakeman** [comment]
Just tried the env var you gave above and it's waiting for propagation now on the latest version, so all good. Just wrapping my head around how the change affected me with multiple/wildcard CNAMEs... was lego taking that wildcard match to mean only applying to the answer?

**Comment by ldez** [comment]
lego tries to follow the CNAME (it's related to the ACME RFC) but your CNAME is a problem because you are not the owner of `pixie.porkbun.com`.

Your DNS configuration is a problem, you have to use your real DNS provider, and add the right CNAME for `service.subdomain.domain.tld`

https://letsencrypt.org/2019/10/09/onboarding-your-customers-with-lets-encrypt-and-acme.html#the-advantages-of-a-cname

**Comment by ldez** [comment]
In fact, I created the option `LEGO_DISABLE_CNAME_SUPPORT` only for me, for debugging purposes.
IMO, the real fix here is to add the right CNAME.
We will see in the future, if we consider is option as a part of the lego "contract".

**Comment by dginhoux** [comment]
I use a wildcard dns entry like "*.dom.tld" cname to a service name entry like "rp1.dom.tld".

Everything work fine.

I can publish a new web app without any change in dns.

And I make from others domains the same thing, with cname pointing on the same service record.

At this time, I've 5 domains, 5 wildcard Le certs... Nothing else. Everything work fine since 2/3 years now.

**Comment by Narice** [comment]
Hi, I had the same issue but went a little further in the debug process.
For home lab use, if you have a dns server running with an SOA record for the zone that you are trying to certify, for example `home.example.com`, make sure to bypass it using `--dns.resolvers 9.9.9.9:53` or your preferred dns server, else the query to porkbun will look like this:
POST `https://porkbun.com/api/json/v3/dns/create/home.example.com`
```json
{
	"secretapikey": "sk1_45fd5c79480e58ac35c22fb22b3b52fe0214bcae0bd3416777eb21cfc764aa64",
	"apikey": "pk1_526181da92ee59f91bd9f63bd1f37c2b0c553289e1ab46c4ccf25bb319919a3d",
	"name": "_acme-challenge",
	"type": "TXT",
	"content": "KNlzbvUGtvxN2HGJ4fly5HogJTtTjdcos-ENRwK9GIY"
}
```
instead of this:
POST `https://porkbun.com/api/json/v3/dns/create/example.com`
```json
{
	"secretapikey": "sk1_45fd5c79480e58ac35c22fb22b3b52fe0214bcae0bd3416777eb21cfc764aa64",
	"apikey": "pk1_526181da92ee59f91bd9f63bd1f37c2b0c553289e1ab46c4ccf25bb319919a3d",
	"name": "_acme-challenge.home",
	"type": "TXT",
	"content": "KNlzbvUGtvxN2HGJ4fly5HogJTtTjdcos-ENRwK9GIY"
}
```
and you will thus get an `Invalid homain.` ERROR message from porkbun instead of your certificate.
Took me a while to spot this, so I hope this will be able to help someone having the same issue in the future.

**Comment by gbakeman** [comment]
I'm curious if you've hosted your own DNS server, have you also considered running one with ACME support? I spent some time awhile ago looking into this, but I've since shelved the idea and forgotten most of what I've learned in that area. 😐

**Comment by Narice** [comment]
No sorry xD
My dns is in my home lab, seperated from the outside for security so I didn't even think about using my own internal dns for the cert signing because I didn't know if it would have worked.
Tho,  here is some good info on doing just what your asking for using Nix/OS: https://nixos.org/manual/nixos/stable/index.html#module-security-acme-config-dns
looks simple enough but I didn't test it out so I can't tell you if the result will be what you want
