### ISSUE TITLE
Support for provider: nsd

### ISSUE THREAD

**Issue by imol-ai** [go-acme/lego#2231]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Other

### Link to the DNS provider

https://www.nlnetlabs.nl/projects/nsd/about/

### Link to the API documentation

https://nsd.docs.nlnetlabs.nl/en/latest/index.html

### Additional Notes

Hey, I know this is not a completely ordinary request, but currently there are not too many options for using lego with a local authoritative DNS server. I found Bindman, which looks like to be quite an old solution, and PowerDns, which is an absolute beast to set up correctly. Nsd is much more simplistic, and can be configured very well declaratively. I know that it doesn't expose what you would traditionally call an API, but I hope that the zone files will work well instead. An implementation can be found [here](https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_nsd.sh).
Thank you in advance.

**Comment by ldez** [comment]
Hello,

I don't know how this tool works exactly, but I understand that it can only be controlled by a CLI.

So in this case you can use the [exec](https://go-acme.github.io/lego/dns/exec/) to execute the commands to inject and clean the response payloads.

You can share your scripts (run by the [exec provider](https://go-acme.github.io/lego/dns/exec/)) in this issue to help the other NSD users.

We will not create a dedicated implementation that uses the CLI because we only accept implementation for HTTP API.

FYI, the `acme.sh` implementation uses the CLI.

**Comment by ldez** [comment]
Also as an alternative, you can use:
- [`RFC2136`](https://go-acme.github.io/lego/dns/rfc2136/)
- [`acme-dns`](https://go-acme.github.io/lego/dns/acme-dns/)

**Comment by imol-ai** [comment]
Alright, thanks a lot! If I come up with something clever, I'll share it here.

**Comment by imol-ai** [comment]
I had problems with DNSSEC on nsd, so I switched to the Knot nameserver, which supports RFC2136. No need to make a script :)
