### ISSUE TITLE
AutoDNS API Support?

### ISSUE THREAD

**Issue by aario** [go-acme/lego#501]
Hi Folks,
I appreciate your efforts and will appreciate much more if lego supports AutoDNS API. There is already a library which written in PHP here:
https://github.com/tillkahlbrock/autodns-api
And the AutoDNS XML API documentation:
https://help.internetx.com/display/API/AutoDNS+XML-API

**Comment by amenk** [comment]
ACME.sh supports AutoDNS --- would be cool to see that in LEGO as well.

https://github.com/tohn/acme.sh/blob/master/dnsapi/dns_autodns.sh

ping @kolaente

**Comment by kolaente** [comment]
Looks fairly doable - from first googling there seems to be only https://github.com/steinhauer-software/internetx-autodns-cli which midght be usable to communicate with autodns, otherwise we'd need to write that ourself.

Unfortunately, the docs linked by @aario are hidden behind a login page and there seems to be no obvious way to register to get access to it, so I'm not really sure if talking to their api is easy or hard.

**Comment by ldez** [comment]
The API documentation seems to be here: https://help.internetx.com/display/APIXMLEN/Domain+Robot+XML+API

**Comment by amenk** [comment]
I believe that only the parts of the API has to be implemented to set the TXT records. It's three XML payloads as shown in https://github.com/tohn/acme.sh/blob/master/dnsapi/dns_autodns.sh

**Comment by amenk** [comment]
I saw that AutoDNS also supports. This seems to be more a standard but I have zero experience with it:

https://help.internetx.com/display/APIEPPEN/Domain+Update

Would it be more interesting to implement EPP? Would that support even more other DNS providers?

**Comment by amenk** [comment]
> I saw that AutoDNS also supports EPP. This seems to be more a standard 

EPP might just only allow to register / modify domains, but not DNS zones. So is not helpful here.

**Comment by amenk** [comment]
@kolaente will implement that in on basis of https://help.internetx.com/display/APIJSONDE

**Comment by kolaente** [comment]
WIP PR is up: #957
