### ISSUE TITLE
Feature request: export DNS help infos

### ISSUE THREAD

**Issue by Klaus-Tockloth** [go-acme/lego#807]
I'm writing my own client based on the lego library. Is it possible that you export the content of dnsHelp() function? The infos there are of general interest.

https://github.com/xenolf/lego/blob/master/cmd/cmd_dnshelp.go

**Comment by ldez** [comment]
I plan to change the change the way that to information of DNS provider are obtained/built: I looking for a way to have more accurate information and to attach the doc to each provider instead of a huge and global function.

Out of curiosity, what are the problems/limitations that make you build your own client?

**Comment by Klaus-Tockloth** [comment]
> I plan to change the change the way that to information of DNS provider are obtained/built: I looking for a way to have more accurate information and to attach the doc to each provider instead of a huge and global function.

That sounds good.

> Out of curiosity, what are the problems/limitations that make you build your own client?

I'm working on the integration of ACME in an enterprise environment, mainly the server side. A fully controllable client is very helpful for functional and load tests.

**Comment by ldez** [comment]
Fixed by #818
