### ISSUE TITLE
registration.Resource is marked for deprecation - what to use instead?

### ISSUE THREAD

**Issue by bouwerp** [go-acme/lego#855]
What should be used instead of the `acme.User` implementation once `registration.Resource` has been deprecated?

**Comment by mxplusb** [comment]
@ldez  can you please provide some commentary on this?

**Comment by ldez** [comment]
Hi all,

I deprecated `registration.Resource` because I think it's not a good abstraction of the `User`.

For now, I don't have a clear idea about the replacement, but I know that I want to replace it.

Maybe I marked `registration.Resource` as deprecated too soon but I want to "freeze" changes on this structure to force us to rethink it.

**Comment by mxplusb** [comment]
I think it might be good to clarify that the intent is to freeze in the documentation and remove the deprecation warning until you are ready to deprecate it. Since modules provide versioning, if you use the library before the formal deprecation, then you'll be fine with doc strings covering intent, if you use the library after the deprecation, then you'd get the warnings from tooling. It's not a very nice user experience when my IDE throws deprecation warnings for things with no replacements.
