### ISSUE TITLE
lego cli fails with LEGO_EXPERIMENTAL_CNAME_SUPPORT

### ISSUE THREAD

**Issue by ralfbecker** [go-acme/lego#865]
I created on an other DNS provider a CNAME to a zone hosted by route53:
```
dig boulder.egroupware.org

;; ANSWER SECTION:
boulder.egroupware.org.	1799	IN	CNAME	boulder.farm.egroupware.org.
boulder.farm.egroupware.org. 299 IN	A	10.44.22.99
```

Running lego with LEGO_EXPERIMENTAL_CNAME_SUPPORT fails:
```
sudo AWS_HOSTED_ZONE_ID=xxxx LEGO_EXPERIMENTAL_CNAME_SUPPORT=true AWS_ACCESS_KEY_ID=yyy AWS_SECRET_ACCESS_KEY=zzz lego --domains boulder.egroupware.org --email rb@egroupware.org --path . --dns route53  run

2019/04/19 11:26:50 [INFO] [boulder.egroupware.org] acme: Obtaining bundled SAN certificate
2019/04/19 11:26:51 [INFO] [boulder.egroupware.org] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/A1JWEeVbklDRnvbTguHvBzl5N5a8C2qfxZm5MA2j7jM
2019/04/19 11:26:51 [INFO] [boulder.egroupware.org] acme: Could not find solver for: tls-alpn-01
2019/04/19 11:26:51 [INFO] [boulder.egroupware.org] acme: Could not find solver for: http-01
2019/04/19 11:26:51 [INFO] [boulder.egroupware.org] acme: use dns-01 solver
2019/04/19 11:26:51 [INFO] [boulder.egroupware.org] acme: Preparing to solve DNS-01
2019/04/19 11:26:51 [INFO] [boulder.egroupware.org] acme: Cleaning DNS-01 challenge
2019/04/19 11:26:52 Could not obtain certificates:
	acme: Error -> One or more domains had a problem:
[boulder.egroupware.org] [boulder.egroupware.org] acme: error presenting token: route53: failed to change record set: InvalidChangeBatch: 
[RRSet with DNS name _acme-challenge.boulder.egroupware.org. is not permitted in zone farm.egroupware.org.]
	status code: 400, request id: 44e7e026-6285-11e9-99fe-a30a7cde5615
```
Looks like LEGO_EXPERIMENTAL_CNAME_SUPPORT=true is not used, and the challenge is created not in the zone the CNAME points too, but the original zone (not registered with Route53).

Ralf

**Comment by mhoran** [comment]
Hey @ralfbecker, the `LEGO_EXPERIMENTAL_CNAME_SUPPORT` flag allows `lego` to set up the challenge at the right-hand side value of the `CNAME` for the `_acme-challenge` record. So, for example:

```
_acme-challenge.boulder.egroupware.org.	3600	IN	CNAME	_acme-challenge.example.com.
example.com NS ns-1967.awsdns-53.co.uk.
```

With `LEGO_EXPERIMENTAL_CNAME_SUPPORT=true`, lego would see the rhs value `_acme-challenge.example.com.` and then resolve that to find out what record to update. In this case, it would try to update `_acme-challenge.example.com` which would be hosted on route53.

I'm not sure what your use case is here, but the intent of `LEGO_EXPERIMENTAL_CNAME_SUPPORT` is so that `lego` can dynamically update records in a zone that is _not_ hosted on route53 (or Cloud DNS, etc.) _or_ to host the records in another zone with limited permissions for the `lego` client.

**Comment by SpComb** [comment]
The `boulder.egroupware.org CNAME ...` does not cover the `_acme-challenge.boulder.egroupware.org` name. You need to have an explicit `_acme-challenge.boulder CNAME ...` in your zone to use `LEGO_EXPERIMENTAL_CNAME_SUPPORT=true`.

**Comment by ralfbecker** [comment]
Thanks, for the answers :)
I got it working.
Ralf
